---
dist: focal
language: ruby
cache: bundler
rvm:
  - 2.5
  - 2.6
  - 2.7
  - 3.0

#before_install: gem install bundler -v 2.1.4

jobs:
  exclude:
    - rvm: 2.7
      gemfile: gemfiles/rails_4.2.gemfile
    - rvm: 3.0
      gemfile: gemfiles/rails_4.2.gemfile

gemfile:
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.gemfile
  - gemfiles/rails_6.1.gemfile

before_install: # use bundler 1.x as long as we need to support rails 4.2
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'

script: bundle exec rake

